AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Peccunia Twitter Serverless Bots
Parameters:
  ImageName:
    Type: String
    Default: tops
    Description: Docker Image Name
  ImageTag:
    Type: String
    Default: latest
    Description: Docker Image Tag
  AssetsBucketArn:
    Type: String
    Default: arn:aws:s3:::peccunia-assets
    Description: Bucket where are present the icons and templates
  KmsArn:
    Type: String
    Default: arn:aws:kms:us-west-2:107982701859:key/fa57f222-b014-4262-8380-9b3b5a4bd551
    Description: Key ARN to Decrypt token secrets

Resources:
  LambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        Tags:
          - Key: "project"
            Value: "Peccunia"
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
            - sts:AssumeRole
        Path: "/"
        Policies:
        - PolicyName: bot_logs_policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:*
              Resource: arn:aws:logs:*:*:*
        - PolicyName: bot_kms_key_policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "kms:Decrypt"
                  - "kms:Encrypt"
                  - "kms:GenerateDataKey"
                  - "kms:DescribeKey"
                  - "kms:ReEncrypt*"
                Resource: !Sub ${KmsArn}
        - PolicyName: bot_bucket_policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                Resource: !Sub '${AssetsBucketArn}/*'

  LambdaTopRobot:
    Type: AWS::Serverless::Function
    DependsOn: LambdaExecutionRole
    Properties: 
      Tags:
        project: "Peccunia"
      PackageType: Image
      Role: !GetAtt LambdaExecutionRole.Arn
      FunctionName: peccunia-twitter-tops-bot
      ImageUri: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ImageName}:${ImageTag}
      Timeout: 30
      KmsKeyArn: arn:aws:kms:us-west-2:107982701859:key/fa57f222-b014-4262-8380-9b3b5a4bd551
      Environment:
        Variables:
          ACCESS_TOKEN: "AQICAHhf60n1JM6idzDOjH5xR4lv7opvhkR06KEKbJxGIfej1AGhAdmlAkeZp8pp2YF2e7SlAAAAkjCBjwYJKoZIhvcNAQcGoIGBMH8CAQAwegYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAw+tsYT0HJ7ogdMa3wCARCATfZaCZRTcRJQczlJAPMI7SW6Gzilol/y5DvaaLyJXoVvfI901Gf3+sISUXml4zTPGeK/ksPTJtF3MHGXnmer7rJu5QGX0s+6WVmgPxIa"
          ACCESS_TOKEN_SECRET: "AQICAHhf60n1JM6idzDOjH5xR4lv7opvhkR06KEKbJxGIfej1AFhxIOAN5tKhH2AwJjbB1C4AAAAjDCBiQYJKoZIhvcNAQcGoHwwegIBADB1BgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDFfwjPFXxghYTP8gTAIBEIBI5bFXhb0kX1afnOlIATaXLu3C/3QGIunFOyu4tU1zfgWbPP86dfPViTvs6WMG1igWZZpoPX+7PpXPRwPUhqOlQOGH9og/Du4R"
          CONSUMER_KEY: "AQICAHhf60n1JM6idzDOjH5xR4lv7opvhkR06KEKbJxGIfej1AFNmfUdSpxNJbvmar5SARa0AAAAdzB1BgkqhkiG9w0BBwagaDBmAgEAMGEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMiWQFvUz2PY8Wd1R+AgEQgDQBAAvdMkhBsii5jy87MhQqN0/RGsy82vqSt3gMMxmhvPSri3wHCXCrf981vCrRk5NmumUH"
          CONSUMER_SECRET: "AQICAHhf60n1JM6idzDOjH5xR4lv7opvhkR06KEKbJxGIfej1AFCBJX5aFFQFfL0lLIr9g50AAAAkjCBjwYJKoZIhvcNAQcGoIGBMH8CAQAwegYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzp4Z3qbcQzAuivF9ICARCATaAJ79ikDUs3cr0wgJ9VkEQMl+0SY1U5MJv5+e4z92y1xZl0MWd+JbrfUKNY1lOk9GJdojooAg426Mjjqtp8kK7IwAtV3SlauKtYQdcp"
      Events:
        TopTrendingEvent:
          Type: Schedule
          Properties:
            Description: 'Todos los días a las 15:12 GMT'
            Schedule: 'cron(12 15 * * ? *)'
            Input: '{"type": "trending", "bucket": "peccunia-assets", "message": "Top 5 Trending Cryptos.\nEdición diaria.\n\n#crypto #bitcoin #cryptocurrency #blockchain #btc #ethereum #money #trading #entrepreneur #bitcoinmining #litecoin #bitcoins #investing #cryptocurrencies #bitcoinnews #eth #trader #investor #business #invest #success #investment"}'
        TopVolumeEvent:
          Type: Schedule
          Properties:
            Description: 'Todos los días a las 10:00 GMT'
            Schedule: 'cron(0 10 * * ? *)'
            Input: '{"type": "daily", "bucket": "peccunia-assets", "message": "Top 5 Cryptos por su volumen en las últimas 24 horas.\nEdición diaria.\n\n#btc #eth #criptomonedas #binance #exchange #investment #bnb #bitcoin #cryptocurrency #blockchain #ethereum #money #trading #bitcoinmining #cryptocurrencies" }'
        TopMarketCapEvent:
          Type: Schedule
          Properties:
            Description: 'Todos los sábados a las 13:07 GMT'
            Schedule: 'cron(07 13 ? * SAT *)'
            Input: '{"type": "weekly", "bucket": "peccunia-assets", "message": "Top 5 Cryptos por Market Cap.\nEdición semanal.\n\n#crypto #bitcoin #cryptocurrency #blockchain #btc #ethereum #money #trading #entrepreneur #bitcoinmining #litecoin #bitcoins #investing #cryptocurrencies #bitcoinnews #eth #trader #investor #business #invest #success #investment" }'
