name: Run packer build on a template file

on:
  push:
    branches:
        - 'master'
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Packer build
        uses: riznob/packer-build-action@v1.1
        with:
          templateFile: 'k8s-microservices/k8s_packer_master.json'
          varFile: 'vars.json'
          workingDir: 'k8s-microservices'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SSH_USERNAME: ec2-user
